---
# This ensures that keepalived is started

- name: Verify
  hosts: all[0]
  order: sorted
  gather_facts: yes
  vars:
    keepalived_install_from_source: true
  tasks:
    - name: Define vrrp nic
      ansible.builtin.set_fact:
        vrrp_nic: "{{ ((ansible_interfaces | reject('equalto', 'lo')) | difference([ansible_default_ipv4.interface])) | sort | first | string }}"

    - name: Show ansible facts
      ansible.builtin.debug:
        var: ansible_facts
        verbosity: 3

    - name: Ensure the first node is master
      ansible.builtin.assert:
        that:
          - "'ipv4_secondaries' in vars['ansible_' + vrrp_nic]"
          - "vars['ansible_' + vrrp_nic]['ipv4_secondaries'][0]['address'] == '192.168.121.2'"
      when: inventory_hostname == ansible_play_hosts[0]
