---
- name: Side effect playbook
  hosts: all
  tasks:
  - name: Stop the service to throw a wrench in the plan
    ansible.builtin.command: "systemctl stop keepalived.service"
    tags:
      - skip_ansible_lint

  - name: Now mask the service to really throw a wrench in the plan
    ansible.builtin.command: "systemctl mask keepalived.service"
    tags:
      - skip_ansible_lint

  - name: Re-collect network facts required after installation iproute
    ansible.builtin.setup:
      gather_subset: network

  - name: Define vrrp nic
    ansible.builtin.set_fact:
      vrrp_nic: "{{ ((ansible_interfaces | reject('equalto', 'lo')) | difference([ansible_default_ipv4.interface])) | sort | first | string }}"

  - name: Define keepalived config
    ansible.builtin.set_fact:
      keepalived_instances:
        internal:
          interface: "{{ vrrp_nic }}"
          state: "MASTER"
          virtual_router_id: 120
          priority: 150
          vips:
            - "192.168.120.2/24 dev {{ vrrp_nic }}"

  - name: Include ansible-keepalived
    ansible.builtin.include_role:
      name: evrardjp.keepalived
