---
# Copyright 2015, Jean-Philippe Evrard <jean-philippe@evrard.me>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Gather variables for each operating system
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts['distribution'] | lower }}-{{ ansible_facts['distribution_version'] | lower }}.yml"
        - "{{ ansible_facts['distribution'] | lower }}-{{ ansible_facts['distribution_major_version'] | lower }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}-{{ ansible_facts['distribution_major_version'] | lower }}.yml"
        - "{{ ansible_facts['distribution'] | lower }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}-{{ ansible_facts['distribution_version'].split('.')[0] }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}.yml"
      paths:
        - "{{ role_path }}/vars"
  tags:
    - always

- name: Configure SELinux
  ansible.builtin.include_tasks:
    file: keepalived_selinux.yml
  when:
    - keepalived_selinux_compile_rules | length > 0
    - ansible_facts['selinux']['status'] is defined
    - ansible_facts['selinux']['status'] == "enabled"
  tags:
    - keepalived-install
    - keepalived-config

- name: Install Keepalived via package manager
  ansible.builtin.include_tasks: install_managed.yml
  when: 
    - keepalived_package_state in ('present', 'latest')
    - not keepalived_install_from_source

- name: Install or uninstall NUT from source
  ansible.builtin.include_tasks: install_from_source.yml
  when: 
    - keepalived_package_state in ('present', 'latest')
    - keepalived_install_from_source

- name: Configure Keepalived
  ansible.builtin.include_tasks: configure.yml
  when: keepalived_package_state in ('present', 'latest')

- name: Uninstall Keepalived
  ansible.builtin.include_tasks: uninstall.yml
  when: keepalived_package_state == 'absent'
