---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  # This is necessary to ensure the _first_ node is indeed master
  order: sorted
  gather_facts: yes
  tasks:
    - name: Show ansible facts
      ansible.builtin.debug:
        var: ansible_facts
        verbosity: 3

    - name: Define vrrp nic
      ansible.builtin.set_fact:
        vrrp_nic: "{{ ((ansible_interfaces | reject('equalto', 'lo')) | difference([ansible_default_ipv4.interface])) | sort | first | string }}"

    - name: Ensure the first node is master
      ansible.builtin.assert:
        that:
          - "'ipv4_secondaries' in vars['ansible_' + vrrp_nic]"
          - "vars['ansible_' + vrrp_nic]['ipv4_secondaries'][0]['address'] == '192.168.33.2'"
      when: inventory_hostname == ansible_play_hosts[0]
