---
- name: Converge
  hosts: all
  tasks:
  - name: Show ansible_interfaces
    ansible.builtin.debug:
      var: ansible_interfaces

  - name: Define vrrp nic
    ansible.builtin.set_fact:
      vrrp_nic: "{{ ((ansible_interfaces | reject('equalto', 'lo')) | difference([ansible_default_ipv4.interface]))[0] | string }}"

  - name: Define keepalived config
    ansible.builtin.set_fact:
      keepalived_install_from_source: true
      keepalived_source_tag: v2.3.2
      keepalived_instances:
        internal:
          interface: "{{ vrrp_nic }}"
          state: "MASTER"
          virtual_router_id: 120
          priority: 150
          vips:
            - "192.168.121.2/24 dev {{ vrrp_nic }}"

  - name: Include ansible-keepalived
    ansible.builtin.include_role:
      name: evrardjp.keepalived
